### ISSUE TITLE
Linked brushing between the visNetwork and plotly visualizations

### ISSUE THREAD

**Issue by julianstanley** [julianstanley/gfpopgui#38]
@tdhock 

This is a big Phase 2 feature that I should be all set to implement now. 

I think it is impossible to have client-side communication between the visNetwork and plotly visualizations.

So, for now, that's going to have to be server-side. My (crude/brute-force) implementation idea right now is just to have a column shared between the changepoint segments and the nodes/edges in the graph. When a user hovers over a point, I can grab that information and use that to change node/edge/changepoint opacity.

**Comment by tdhock** [comment]
"I think it is impossible to have client-side communication between the visNetwork and plotly visualizations" --- nothing is impossible!!! and conceptually there is no reason why this should not be possible (all of the data is already in the browser).

but I guess it would be difficult / hard hack? Can you please explain why? it seems like plotly has support for that so the problem is on the visNetwork side? I would suggest opening an issue with visNetwork to discuss the problem and possible solutions.

For now I think it is OK to go through the server but I think that will be too slow for the kind of interactions I had in mind:
- hover over node -> highlight corresponding segments
- hover over edge -> highlight corresponding changepoints
- hover over segment -> highlight corresponding node + other segments with same node
- hover over changepoint -> highlight corresponding edge + other changepoints with same edge

if you really have to hit the server for this kind of interaction, I would suggest using a click instead of a hover. (we typically expect quicker reaction times from hovers than for clicks) Does that make sense?

**Comment by julianstanley** [comment]
>nothing is impossible!!! 

Indeed :laughing:

>but I guess it would be difficult / hard hack?

Yeah, better phrasing would be "I don't know how to do it and suspect it would be difficult". 

**Background**

Client-side crosstalk between two htmlwidget objects can be accomplished with the `crosstalk` package. For example, [figure 17.31 in the plotly book](https://plotly-r.com/linking-views-with-shiny.html). There might be other options that I don't know about.

The actual process of client-side crosstalk is still a big black box for me (that's on my _to-learn-about_ list), but I've used the `crosstalk` package to connect two plotly graphs and it was super quick and easy.

**`crosstalk` with visNetwork**

Since visNetwork is built on htmlwidgets, it should work with `crosstalk`. The `crosstalk` devs provide [instructions](https://rstudio.github.io/crosstalk/authoring.html) to make any htmlwidget package `crosstalk`-compatible (meaning that it can communicate with any other `crosstalk`-compatible widget).

Someone brought up [visNetwork `crosstalk` support in January 2018 (here)](https://github.com/datastorm-open/visNetwork/issues/229). Benoit seemed supportive & opened a branch a few days later, but hasn't made any progress since. I commented at the bottom of that issue about a month ago.

I can give that implementation a shot, but I suspect it'll be a decently-involved learning process. But, maybe there's an easier way?

> if you really have to hit the server for this kind of interaction, I would suggest using a click instead of a hover. (we typically expect quicker reaction times from hovers than for clicks) Does that make sense?

That totally makes sense! 

I think, to move forward with this, I think it might be reasonable to *first* implement those 4 interactions the server-hitting way with clicks. That'll give us an idea of whether hitting the server makes it impossibly slow, and that implementation should be pretty quick (<1 week, I think?)

Once that's done, I can try to implement proper crosstalk. That might end up being easy, or might end up being a huge time suck--I don't have enough background yet to know either way.

**Comment by julianstanley** [comment]
Yesterday and today I implemented linked brushing from plotly-->visNetwork. I couldn't figure out how to do it completely client-side yet, but the server-hitting side with _hover_, not with a click, actually works reasonably quickly on the shiny server. Still not ideal, but that's nice.
